### ISSUE TITLE
Tips JSON changes

### ISSUE THREAD

**Issue by tellowkrinkle** [07th-mod/tsumihoroboshi#19]
In the switch from hardcoded tips to a JSON file, tip 29 got a censored version pulled from the console release, changing from `お気に入りのワイン` to `お気に入りの飲み物`.  Is that what we wanted?

In addition, I personally think tip 34, `やつら`, whose English title was `The Others` in the hardcoded tips and is `"They"` in the JSON, should be changed to `"Them"`, and tip 37, `悪魔の脚本` should be renamed from `The Demon's Script` to `The Demons' Script`.

**Comment by InochiPM** [comment]
The censoring of "Wine" vs "Drinks" isn't that much of a big deal to me, Since i think the tips it corresponds to also discloses what those drinks are? If it's more than just wine then the title makes sense to me. 
"やつら" loosely translates to (they; those guys​) from what my dictionary tells me, but i can also see how you could change it to "Them".

The last one makes so much more sense because im the one who wrote it wrong lmao so i believe we should change it to that as well.

**Comment by tellowkrinkle** [comment]
Ahh.  I assumed it was unintentional because the English version still uses `Wine`.  I feel like we should keep them consistent, though I don't care which one we go with.

For the `やつら` one, I just feel like `"They"` doesn't make for a very good title.

**Comment by idealpersona** [comment]
I don't know what this is called grammatically, but when I see "They" I always expect a verb to follow - never appearing on its own, whereas "Them" is the opposite; it can appear on its own or as a direct/indirect object and a verb should not follow.

So "they played a game" makes sense, but "them played a game" does not.
And "we played a game with they" does not make sense, but "we played a game with them" does.

So "Them" is definitely a better title.

**Comment by orian34** [comment]
The current "gettip_tsum026.png"
![image](https://user-images.githubusercontent.com/12663654/50402798-9ef8b180-0799-11e9-8e33-1941ad37f853.png)
And current "gettip_tsum009.png"
![image](https://user-images.githubusercontent.com/12663654/50402804-addf6400-0799-11e9-9050-52c9bb0e3c63.png)

Posted this because the displayed names in the tips menu are not the same.
"The Demon's Script" and "My Very Favorite Wine"
Don't forget to change it when you settle for one.
