### ISSUE TITLE
Partial Release(s) for Tsumihoroboshi

### ISSUE THREAD

**Issue by enumag** [07th-mod/tsumihoroboshi#6]
Right now it seems that voice patch and DLL updates will be complete quite soon while the PS3 graphics patch will need a few more weeks to finish (~1 month but it could be longer if we run into some problems). LipSync is just a matter of upgrading the scripts with my compiler and then compiling the sprite packs + the DLL changes so we're good on this front at well.

For better time management while we wait for the graphics patch I came up with an idea of partial patch for Tsumihoroboshi. This patch would have all the features including adv mode, lipsync etc. but would only cover first several days (roughly 1/3 of the game). The purpose is to get an early feedback about all the new features so that we can make the main release right after the PS3 patch is done. While this seems like a good idea there are some details we should consider here.

Firstly @Grelo reminded me that he often goes back to the scripts he previously completed to make some improvements. Because of this we don't want the community to start reading the game with the partial patch en masse. They will get a better experience if they wait a bit longer. While you might argue that we're making small improvements to previous chapters all the time, we should at least make the most basic improvements before the first release in order to not make the patch feel half-baked.

With that in mind I prefer to only make one such release instead of several and intentionally describe it as "Tsumihoroboshi testing release" and not "Tsumihoroboshi patch part 1".

Another thing to consider is how public should the patch be. Of course the link will be public somewhere to whoever finds it, but the question is if we should make a public annoncement and tag a pre-release on GitHub or keep it a bit more under wraps and only link it dev channel on Discord or something. In my opinion it should be fine to make it public if the release notes clearly state that the part it covers is by no means considered complete.

Can you give me your opinions on how we should handle this?

- Should we make a partial release at all?
- How many of such partial releases should we make?
- Should we fluff it as "testing release" or "final release part 1"?
- Should we tag a public pre-release on GitHub and/or announcement on Discord?

**Comment by ItaloKnox** [comment]
I'm all in for partial patches with incremental updates. I think this is a good way of keeping the community expectations in check and get feedback. Having just a slice of the chapter would be good to get feedback and fix bugs since the people playing it are going to be reporting a lot more and a lot faster. This will give us the chance of fixing more issues as we keep adding more chapters and reach 1.0 with a patch as stable as previous chapters that have gotten to this point only two or three versions later.

In my opinion, we should just go with a public release with everything that a full chapter deserves, including the installer. We can just put some big warning that everything is work in progress. I would even go as far as adding a "Work in progress - version 0.***" in the corner of the game as a watermark. It is always good to have the community involved with the development of the project. Those who are looking forward and can't wait to play it will be more likely to report issues if we encourage them to take part in the process.

**Comment by VocalNight** [comment]
I agree with Italo. I think a partial patch with public release sounds like a good idea to catch bugs and receive feedback. Users are the best testers afterall.

**Comment by Grelo** [comment]
Hate to be the one having negative view on this.
You think the public will download partial patch just to report bugs? No one wants to have "partial" first experience with this release and then wait weeks for it to be finished. If i was in their shoes i would wait for the whole patch.
Like I said to @enumag I am for 1 partial release before the whole patch comes out. For feedback and bug fixes. It would be best around 1/3.

**Comment by ItaloKnox** [comment]
I don't think it has to receive updates so frequently. If we slice the game into three parts and release updates incrementally it can save us a lot of time. Everyone would have full knowledge that the game is not yet complete, so I see no scenario where this is different from the lipsync and movie pre-releases. In fact, these two only proved that the community wants to be more involved with the patch and give feedback about it. We have the opportunity of getting bug reports early and release v1.0 in a state that would be much more polished than every chapter released before.

In all honesty, I think it doesn't hurt to try this at least once. If it doesn't work, we don't have to repeat the process in Ch.7. If it does work, we still win.

**Comment by orian34** [comment]
I think it's worth a try, as Italo said. The people who want to enjoy the finished patch for full quality will just hold off, while the more proactive people will gladly help finding issues, I'd think. 

I can't disagree as well that the first for some people will be somewhat spoiled by not having a top notch experience, but I'd think they're aware of what they're doing by getting an experimental release for bugfixing.

I'd say, let's try, and if it doesn't go well, we can still roll back, but it can help too, maybe?

As for the next ones, well...
Mh, Chapter 7 will be another beast.

**Comment by DoctorDiablo** [comment]
I'm willing to give this a try, but I'm feeling a little hesitant about it too.  Getting feedback and finding bugs sooner are both great, but I don't want work on the partial release to slow down progress on the full release.  Basically, the rest of us should handle any issues that get reported instead of piling more work on Grelo's plate.  And I feel like users will be annoyed to have the patch stop right as the story is picking up.

We also need to make it very clear that it's a partial patch.  It's not something we've done before, so users won't expect it.  If we're going to add it to the installer, we need to add red text saying it's a partial patch, or the graphic needs to be grayed out or something.  Maybe we can also add a splash screen on startup that says as much (with a dumb picture of Rena wearing a construction hat!)  And we need to somehow indicate where the partial patch ends, maybe add another screen that says "rest of patch still in development, thanks for playing."

**Comment by ItaloKnox** [comment]
Yes, I think the point (and why I'm so positive with this) is that we are going to work on the issues while Grelo clearly focuses on finishing the game. I never intended to push more work to him. Most of the issue might be fixed with code, so I think we should be fine. But even if we get things that are clearly within our reach, I think the team should handle that, even more, when we have a lot of idle people during this stage.

About the installer, I have plans to adapt it especially to handle this pre-release. Buttons for install, update, and backup. This will be especially great because I get to test these features to their best right of the bat. I'm also all in for including a warning in game about the current status of the patch. Would be even better if the user can't skip it.

**Comment by enumag** [comment]
I feel a bit hesitant about enabling the installer but with an unskippable warning screen in the game I can agree.

How many of these partial releases would you like to make?
